-- Snapshots de volumen A→B del fluxómetro (sesión procedural).
-- No es caudal L/min de producto: session_liters vs target_liters.
-- Escalable: sensor_id 0..N (hoy solo id=0, role=dilution).

BEGIN;

CREATE TABLE IF NOT EXISTS public.hydro_flow_readings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  sensor_id smallint NOT NULL DEFAULT 0,
  role text NOT NULL DEFAULT 'dilution',
  phase text,
  session_liters double precision NOT NULL DEFAULT 0,
  target_liters double precision,
  active boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS hydro_flow_readings_device_created_idx
  ON public.hydro_flow_readings (device_id, created_at DESC);

CREATE INDEX IF NOT EXISTS hydro_flow_readings_device_sensor_idx
  ON public.hydro_flow_readings (device_id, sensor_id, created_at DESC);

COMMENT ON TABLE public.hydro_flow_readings IS
  'Volumen procedural A→B por fluxómetro (session vs target). L/min no es métrica de producto.';
COMMENT ON COLUMN public.hydro_flow_readings.session_liters IS
  'Litros acumulados desde reset de sesión (inicio del tramo A→B)';
COMMENT ON COLUMN public.hydro_flow_readings.target_liters IS
  'Target del procedimiento (ej. dilución); nullable si solo se cuenta';
COMMENT ON COLUMN public.hydro_flow_readings.role IS
  'dilution | drain | fill | irrigate | generic';
COMMENT ON COLUMN public.hydro_flow_readings.phase IS
  'Opcional: diluting_draining | diluting_filling | etc.';

COMMIT;

SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'hydro_flow_readings'
ORDER BY ordinal_position;
